# source: https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb

IMAGENET_TEMPLATES = [
    "a photo of a {}.",
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
]

IMAGENET_TEMPLATES_SELECT = [
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
]


PACS_TEMPLATES = [
    "itap of the {}.",
    "a sketch of a {}.",
    "a drawing of a {}.",
    "graffiti of a {}.",
    "a sketch of the {}.",
    "a painting of a {}.",
    "a cropped photo of a {}.",
    "a pixelated photo of a {}.",
    "a painting of the {}.",
    "a rendering of a {}.",
    "a embroidered {}.",
    "a black and white photo of the {}.",
    "a tattoo of a {}.",
    "a bright photo of a {}.",
    "a bad photo of a {}.",
    "a plastic {}.",
    "a {} in a video game.",
    "a doodle of a {}.",
    "a blurry photo of a {}.",
    "a photo of one {}.",
    "a bright photo of a {}.",
    "a black and white photo of the {}.",
    "a photo of a {}.",
    "a photo of one {}.",
    "a drawing of a {}.",
    "a bad photo of a {}.",
    "a cropped photo of a {}.",
    "a {} in a video game.",
    "a bright photo of the {}.",
    "a close-up photo of the {}.",
    "a photo of many {}.",
    "a photo of a nice {}.",
    "a bad photo of the {}.",
    "a photo of the {}.",
    "a photo of a clean {}.",
    "a painting of a {}.",
    "a dark photo of the {}.",
    "a blurry photo of a {}.",
    "a sculpture of a {}.",
    "a sketch of a {}.",
    "itap of the {}.",
    "a sketch of a {}.",
    "a drawing of a {}.",
    "graffiti of a {}.",
    "a sketch of the {}.",
    "a painting of a {}.",
    "a cropped photo of a {}.",
    "a pixelated photo of a {}.",
    "a painting of the {}.",
    "a rendering of a {}.",
    "a embroidered {}.",
    "a black and white photo of the {}.",
    "a tattoo of a {}.",
    "a bright photo of a {}.",
    "a bad photo of a {}.",
    "a plastic {}.",
    "a {} in a video game.",
    "a doodle of a {}.",
    "a blurry photo of a {}.",
    "a photo of one {}.",
    "a jpeg corrupted photo of a {}.",
    "a bad photo of a {}.",
    "itap of the {}.",
    "a bright photo of a {}.",
    "a {} in a video game.",
    "a black and white photo of the {}.",
    "a photo of a {}.",
    "a drawing of a {}.",
    "a close-up photo of a {}.",
    "a photo of one {}.",
    "a close-up photo of the {}.",
    "a bad photo of the {}.",
    "a photo of a nice {}.",
    "a cropped photo of a {}.",
    "a sculpture of a {}.",
    "a photo of the {}.",
    "a bright photo of the {}.",
    "a pixelated photo of a {}.",
    "a photo of a clean {}.",
    "a good photo of the {}."
]
